//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAnimalia.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraComprobante
    {
        public System.Guid IdCabeceraComprobante { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTimeOffset> Fecha { get; set; }
        public Nullable<System.Guid> IdTipoComprobante { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<System.Guid> IdDetalleComprobante { get; set; }
        public Nullable<bool> Cobrada { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual DetalleComprobante DetalleComprobante { get; set; }
        public virtual TipoComprobante TipoComprobante { get; set; }
    }
}
