//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAnimalia.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public System.Guid IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Apellido { get; set; }
        public string Mascota { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<System.Guid> IdProducto { get; set; }
        public Nullable<System.DateTime> FechaProximaCompra { get; set; }
        public string Codigo { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
