//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAnimalia.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AmountProductAsoc = new HashSet<AmountProductAsoc>();
        }
    
        public string Codigo { get; set; }
        public string Name { get; set; }
        public string Desciption { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> Kg { get; set; }
        public System.Guid IdProducto { get; set; }
        public string BarCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountProductAsoc> AmountProductAsoc { get; set; }
    }
}
